In [2]:
import numpy as np

In [7]:
a=np.array([[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]])

In [8]:
a.shape

(1, 3, 4)

In [9]:
a.size

12

In [10]:
a.ndim

3

In [14]:
a[0,0]

array([1, 2, 3, 4])

In [15]:
a[0,2,3]

12

In [18]:
a[a % 2 == 1]

array([ 1,  3,  5,  7,  9, 11])

In [23]:
x = np.random.random((3, 3))

In [24]:
x

array([[0.6436136 , 0.83215945, 0.77297285],
       [0.00502131, 0.00351099, 0.96781235],
       [0.84155921, 0.70918667, 0.63285964]])

In [17]:
np.resize(a,(4,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [16]:
np.transpose(a)

array([[[ 1],
        [ 5],
        [ 9]],

       [[ 2],
        [ 6],
        [10]],

       [[ 3],
        [ 7],
        [11]],

       [[ 4],
        [ 8],
        [12]]])

In [29]:
a=np.array([[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]])
b=np.array([[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]])

In [31]:
#index wise multiplication
np.multiply(a,3)

array([[[ 3,  6,  9, 12],
        [15, 18, 21, 24],
        [27, 30, 33, 36]]])

In [32]:
#matrix multi
np.multiply(a,b)

array([[[  1,   4,   9,  16],
        [ 25,  36,  49,  64],
        [ 81, 100, 121, 144]]])

In [33]:
#adding both matices
np.add(a,b)

array([[[ 2,  4,  6,  8],
        [10, 12, 14, 16],
        [18, 20, 22, 24]]])

In [34]:
#subtract b from a
np.subtract(a,b)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [35]:
#divide b by a
np.divide(b,a)

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [28]:
np.linalg.inv(x)

array([[-2.90783334e+00,  9.15609920e-02,  3.41159754e+00],
       [ 3.44829231e+00, -1.03362602e+00, -2.63104206e+00],
       [ 2.57715051e-03,  1.03653285e+00, -8.15562178e-03]])

In [26]:
np.reshape(a,(2,6))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])